/* 独立模型视图；保留原媒体表及武器属性榜。 */
const modelData=window.TACTICAL_DATA,modelEngine=window.TACTICAL_MODEL;
const modelState={mode:'model',preset:'balanced',route:'best',build:'auto',skills:'developed',query:'',filter:'all',weights:null};
const savedMediaRankPage=characterRankPage;
const modelNumber=v=>Math.round(v);
const modelRange=r=>r[0]===r[1]?String(Math.round(r[0])):Math.floor(r[0])+'–'+Math.ceil(r[1]);
const modelSource=id=>modelData.sources.find(s=>s.id===id);
const modelSourceLink=id=>{const s=modelSource(id);return s?dbSource(s):''};
const modelText=t=>String(t||'').replaceAll('HP','生命值').replaceAll('Blaze Arts','焰技').replaceAll('Blaze Art','焰技').replaceAll('Overblaze','爆焰状态').replaceAll('Draw Back','后撤').replaceAll('Nosferatu','吸血魔法').replaceAll('RPG Site','角色扮演游戏站').replaceAll('Pocket Tactics','口袋战术').replaceAll('Serenes Forest','宁静之森');
function modelModes(){return '<div class="model-modes" role="group" aria-label="角色评价方式">'+[['model','本站模型'],['compare','多站对照'],['media','原始分档']].map(([k,l])=>'<button data-model-mode="'+k+'" aria-pressed="'+(modelState.mode===k)+'">'+l+'</button>').join('')+'</div>'}
characterRankPage=function(){return modelModes()+(modelState.mode==='media'?savedMediaRankPage():modelState.mode==='compare'?modelComparisonPage():modelRankingPage())};
function modelOptions(){return{preset:modelState.preset,route:modelState.route,build:modelState.build,skills:modelState.skills,weights:modelState.weights}}
function modelResults(){return modelEngine.rank(modelData.characters,modelOptions())}
function modelSearch(r){return [r.name,r.originalName,...r.aliases,...r.roleTags].join(' ').toLowerCase().includes(modelState.query.trim().toLowerCase())}
function modelSettings(){return '<div class="model-settings"><label>使用场景<select id="model-preset">'+Object.entries(modelEngine.presets).map(([id,p])=>'<option value="'+id+'" '+(id===modelState.preset?'selected':'')+'>'+p.label+(modelState.weights&&id===modelState.preset?' · 已调权重':'')+'</option>').join('')+'</select></label><label>第一部路线<select id="model-route">'+[['best','各自最易招募路线'],...['凯伊','迪托利希','赛奥朵拉','蕾达'].map(t=>[t,t])].map(([id,l])=>'<option value="'+id+'" '+(id===modelState.route?'selected':'')+'>'+l+'</option>').join('')+'</select></label></div><details class="model-advanced"><summary>培养方向与技能配置 <span>'+({auto:'按已知资质',physical:'物理方向',magic:'魔法方向'}[modelState.build])+' · '+(modelState.skills==='fixed'?'只计固有机制':'已学并装备强化技')+'</span></summary><div class="model-settings"><label>培养方向<select id="model-build">'+[['auto','按已知资质选择'],['physical','物理方向'],['magic','魔法方向']].map(([id,l])=>'<option value="'+id+'" '+(id===modelState.build?'selected':'')+'>'+l+'</option>').join('')+'</select></label><label>技能配置假设<select id="model-skills"><option value="fixed" '+(modelState.skills==='fixed'?'selected':'')+'>只计固有机制</option><option value="developed" '+(modelState.skills==='developed'?'selected':'')+'>已学并装备强化技</option></select></label></div></details>'}
function modelWeights(){const p=modelEngine.presets[modelState.preset],w=modelState.weights||Object.fromEntries(modelEngine.keys.map((k,i)=>[k,p.weights[i]])),sum=Object.values(w).reduce((s,x)=>s+x,0);return '<details class="model-weights"><summary>调整七项权重 <span>'+modelEngine.keys.map(k=>modelEngine.names[k]+' '+(sum?Math.round(w[k]/sum*100):0)+'%').join(' · ')+'</span></summary><div class="model-weight-grid">'+modelEngine.keys.map(k=>'<label>'+modelEngine.names[k]+'<input type="number" min="0" max="100" step="1" data-model-weight="'+k+'" value="'+w[k]+'" aria-label="'+modelEngine.names[k]+'权重"></label>').join('')+'</div><p>输入相对权重，系统按总和归一化；0 表示忽略该项。<button class="model-text-button" data-model-reset>恢复当前场景</button></p></details>'}
function modelRankingPage(){const results=modelResults(),valid=results.every(r=>r.valid),eligible=results.filter(r=>r.eligible),list=results.filter(r=>modelSearch(r.character)&&(modelState.filter==='all'||modelState.filter==='ranked'&&r.eligible||modelState.filter==='pending'&&!r.eligible));return '<div class="model-intro"><div><strong>七维培养评价 <span>试行版 1.0</span></strong><p>依据成长、技能与招募事实计算；技能判读及权重公开可调。媒体分档不参与打分。</p></div><a href="#model-method" data-model-method>查看公式与局限 ↓</a></div>'+modelSettings()+modelWeights()+'<div class="db-content model-content"><div class="model-toolbar"><label class="model-search"><span>⌕</span><input id="model-query" type="search" aria-label="搜索模型角色" placeholder="搜索姓名、别名或能力标签…" value="'+esc(modelState.query)+'"></label><select id="model-filter" aria-label="筛选评价状态">'+[['all','全部 63 人'],['ranked','可计算名次 '+eligible.length+' 人'],['pending','资料不足或本路线不可用 '+(63-eligible.length)+' 人']].map(([id,l])=>'<option value="'+id+'" '+(id===modelState.filter?'selected':'')+'>'+l+'</option>').join('')+'</select></div><div class="model-result-note"><strong>'+list.length+' 名角色</strong><span>指数高者优先；范围重叠表示名次可能改变</span></div>'+(valid?'<div class="data-table-wrap"><table class="data-table model-table"><thead><tr><th>序位</th><th>角色 / 特点</th><th>模型指数 <small>0–100</small></th><th>证据覆盖</th><th>两站参考</th><th>依据</th></tr></thead><tbody>'+list.map(r=>modelRow(r)).join('')+'</tbody></table></div>':'<div class="model-empty" role="alert">至少设置一项非零权重，才能计算模型。</div>')+(!list.length&&valid?'<div class="model-empty">没有匹配角色。<button data-model-clear class="model-text-button">清除搜索与筛选</button></div>':'')+'</div><p class="model-caption">“模型指数”是有条件的培养参考，不是实测伤害、胜率或官方结论。证据覆盖不乘入强度分；未知项扩大范围，覆盖不足时不强排。</p>'+modelMethod();}
function modelRow(r){const c=r.character,media=c.media;return '<tr class="'+(!r.eligible?'model-pending':'')+'"><td><span class="model-rank">'+(r.eligible?r.rank:'—')+'</span></td><th scope="row"><button class="entry-name" data-model-character="'+c.id+'">'+esc(c.name)+'<small>'+esc(c.roleTags.slice(0,2).join(' · ')||'机制待补证')+'</small></button></th><td><strong class="model-score">'+(r.eligible?modelNumber(r.score):r.available?'待定':'本路线不可用')+'</strong><small class="model-range">资料与假设范围 '+modelRange(r.range)+'</small></td><td><span class="coverage-bar"><i style="width:'+Math.round(r.coverage*100)+'%"></i></span><span>'+Math.round(r.coverage*100)+'% · '+r.confidence+'</span></td><td class="model-media-cell"><span title="口袋战术">口袋 '+(media.ptTier||'—')+'</span><span title="核心玩家">核心 '+(media.kgTier|| (media.kgLordRank?'主角第'+media.kgLordRank:'—'))+'</span></td><td><button class="row-detail" data-model-character="'+c.id+'">拆解 ↗</button></td></tr>'}
function modelMethod(){return '<details class="ranking-method" id="model-method"><summary>模型公式、评分锚点与未覆盖因素</summary><div><p><strong>指数 = 各维度分数 × 归一化权重之和。</strong>区间上下界分别加权；显示的整数指数是范围中点，用于临时排序。同整数并列，详情给出可能序位。模型区间不是统计置信区间。</p><div class="model-formulas"><p><b>输出潜力</b>：主攻击成长×60% + 速度×25% + 技巧×15%，再÷70×100。自动方向只在已知武器/魔法资质中选择；可手动指定物理或魔法，不代表已经转职。</p><p><b>生存潜力</b>：生命成长×35% + 防守×40% + 魔防×25%，再÷70×100。两项都使用固定70的归一化锚点并封顶100。穆采用个人技能后的成长，技能维不再重复奖励。</p><p><b>个人机制 / 团队支援</b>：按来源效果进行本站人工判读，公开每人的区间与条件。0表示未提供额外机制，约25表示局限较强，约50表示有明确持续价值，约75以上表示覆盖广或可压缩行动。概率、阶段、武器、生命及站位条件折扣后取范围；同一效果只归一维。白魔术资质仅作22分的支援入口代理，不保证已学治疗。</p><p><b>机动适性</b>：无骑飞资质40，骑术65，飞行75取最高；已确认移动机制另加，禁止骑飞的角色20。数值不是移动格数。<b>培养适性</b>：基础30 + 每项目标方向武器/魔法资质20，上限90；不再次使用成长和骑飞资质。</p><p><b>入队成本</b>：第一/二/三部基准100/60/25；减去支援级×4、名声级×2、每千金钱×2（最多24）、每种物品6（最多12）、每任务6（最多18）、每外传10（最多18）、其他条件4（最多12）。这些是本站成本锚点，不是游戏兑换公式。本路线数值冲突逐字段传播，支援/名声/金钱未知时分别保留0–3级、0–10级、0–12000金钱的模型范围，未知支出不按免费处理。最易路线按这套成本代理选取，不是实测最快路线。</p></div><p>“只计固有机制”使用固定个人能力；“已学并装备强化技”假设具备有据的额外技能，+版替代旧版。不凭行序指定实际解锁等级。涉及幸运、力量、魅力或当前生命的触发率使用20–40的情境范围；其他未明条件通常以25%–75%覆盖判读，具体例外见角色说明。</p><p><strong>缺失与冲突</strong>：未知维度保留0–100范围；证据覆盖按有充分输入的维度权重累计。覆盖不足80%，或仍在使用的输出/生存/个人机制维度缺关键数据，则只列待定。将一项权重设为0会跳过该项门槛。不因资料少而判为弱。角色在所选第一部路线不能招募时单列不可用，不能理解为后续全流程不可用。</p><p><strong>尚未建模</strong>：入队能力与实际等级、职业成长和职业基础修正、全战技与技能装备槽竞争、实际武器重量与体格、敌人攻防/攻速阈值、地图目标/地形频率、支援组合、有限资源分配及补丁差异。当前版本不能得出统一难度下的最强实战队伍。</p><p>资料来自宁静之森、游民星空、角色扮演游戏站；口袋战术与核心玩家供独立观点对照。转载同一作者的页面不算额外独立证据。核查日期：2026.09.25。</p></div></details>'}
function modelComparisonPage(){const list=modelData.characters.filter(modelSearch);return '<div class="model-intro"><div><strong>观点分歧直接对照</strong><p>两榜可比较的 46 人中，18 人同档、28 人不同档。不同范围和标准不能简单求平均。</p></div></div><div class="model-source-cards"><article><h2>口袋战术</h2><p>57 人跨阶段分档；排除四主角及伊修玛尔。未公布统一难度和量化权重。</p>'+modelSourceLink('pt-tier')+'</article><article><h2>核心玩家</h2><p>46 名第一部招募角色，考虑定位、个人技能与最易路线成本；四主角另排行。</p>'+modelSourceLink('kg-tier')+'</article></div><div class="db-content"><div class="model-toolbar"><label class="model-search"><span>⌕</span><input id="model-query" type="search" aria-label="搜索模型角色" placeholder="搜索要对照的角色…" value="'+esc(modelState.query)+'"></label></div><div class="data-table-wrap"><table class="data-table model-comparison"><thead><tr><th>角色</th><th>口袋战术</th><th>核心玩家</th><th>对照结果</th></tr></thead><tbody>'+list.map(c=>{const m=c.media;return '<tr><th scope="row"><button class="entry-name" data-model-character="'+c.id+'">'+esc(c.name)+'</button></th><td>'+esc(m.ptTier||'未分档')+'</td><td>'+esc(m.kgTier||(m.kgLordRank?'主角第 '+m.kgLordRank+' 位':'不在此榜范围'))+'</td><td><span class="'+(m.agreement==='different'?'model-disagreement':'')+'">'+(m.agreement==='different'?'有分歧':m.agreement==='same'?'同档':'范围不同，不比较')+'</span></td></tr>'}).join('')+'</tbody></table></div></div><p class="model-caption">多网站不等于多份独立实测。17173相关分析转载游民，后者署名原作者来自小红书；这一链条不作三票。本模型由原始数值、技能与条件生成，媒体档位不会改变计算结果。</p>';}
function showModelCharacter(id){const c=modelData.characters.find(x=>x.id===id);if(!c)return;const r=modelEngine.evaluate(c,modelOptions());if(!r.valid)return toast(r.reason);const peers=modelResults(),ranked=peers.find(x=>x.character.id===id);const fSources=[...new Set([...(c.evidence||[]).map(x=>x.sourceId),...c.abilities.filter(a=>a.description).map(x=>x.sourceId)])].map(modelSource).filter(Boolean);const pic=D.characters.find(x=>x.id===id);const growth=c.effectiveGrowthRates||c.growthRates;
 detailShell(c.name,'本站模型 1.0 · '+(r.build==='magic'?'魔法方向':'物理方向'),'<div class="model-detail-intro">'+(pic?'<img src="assets/'+pic.portrait+'" alt="'+esc(c.name)+'官方插图">':'')+'<div><strong class="model-detail-score">'+(r.eligible?modelNumber(r.score):'待定')+'</strong><p>资料与假设范围 '+modelRange(r.range)+' · 证据覆盖 '+Math.round(r.coverage*100)+'%</p><p>'+(ranked.eligible?'当前序位 '+ranked.rank+'；区间允许的序位 '+ranked.rankRange.join('–'):'资料不足或所选第一部路线不可招募，不强排。')+'</p></div></div><p class="field-help">原文姓名：'+esc(c.originalName)+'。这是启发式培养指数，分值不代表实测伤害或胜率。</p><h3>七项拆解</h3><div class="model-dimension-list">'+modelEngine.keys.map(k=>{const d=r.dimensions[k];return '<section><div><strong>'+modelEngine.names[k]+'</strong><span>'+modelRange(d.range)+' / 100 · 权重 '+Math.round(r.weights[k]/r.totalWeight*100)+'%</span></div><div class="dimension-track"><i style="left:'+d.range[0]+'%;width:'+Math.max(1,d.range[1]-d.range[0])+'%"></i><b style="width:'+((d.range[0]+d.range[1])/2)+'%"></b></div><p>'+esc(d.note)+'</p></section>'}).join('')+'</div><h3>个人成长率'+(c.effectiveGrowthRates?' · 已含成长型个人技能':'')+'</h3>'+(growth?'<div class="stat-grid">'+Object.entries(growthNames).map(([k,label])=>'<div><span>'+label+'</span><strong>'+modelRange(modelEngine.growth(c,k))+'%</strong></div>').join('')+'</div><p class="field-help">区间表示来源差异；未计职业成长，不是当前能力。'+(c.effectiveGrowthRates?'穆九项成长已应用一次+20个百分点，未重复加成。':'')+'</p>':'<p>成长率未收录，模型保留未知范围。</p>')+'<p>技能资质：'+esc(c.proficiencies.length?c.proficiencies.join('、'):'未收录')+'</p><h3>个人能力与条件</h3><p class="field-help">中文能力名为工作译名。强化版替代旧版；具体学习等级尚未逐项核实。宣传或客串机制保留出处，不能当正式版完整数据。</p><div class="model-abilities">'+c.abilities.map(a=>'<article><h4>'+esc(modelText(a.nameZh||'未公开能力'))+'</h4><p>'+esc(modelText(a.description||'资料未公布'))+'</p><small>条件：'+esc(modelText(a.trigger||'未确认'))+'</small>'+(a.sourceId?'<div>'+modelSourceLink(a.sourceId)+'</div>':'')+'</article>').join('')+'</div><h3>可得性与成本</h3><p>'+esc(modelText(c.availability.routeNote))+'</p><p>'+esc(modelText(c.availability.costNote))+'</p>'+((c.conflicts||[]).length?'<h3>来源差异 '+c.conflicts.length+' 项</h3><div class="model-conflicts">'+c.conflicts.map(x=>'<p>'+esc(modelConflictText(x))+'</p>').join('')+'</div>':'')+'<h3>资料出处</h3><div class="record-sources">'+inlineSources(fSources)+'</div><p class="field-help">评分区间和折扣属于本站模型设计；链接支持游戏事实，并不代表来源认同本站分数。</p><button class="button" data-model-legacy="'+id+'">查看原媒体分档与已有档案 ↗</button>');
}
function modelConflictText(x){const field=String(x.field||'条件').replace('growthRates.','成长率：').replace('availability.','入队：');const translated=field.replace(/hp|strength|magic|speed|dexterity|defense|resistance|luck|charm/g,k=>growthNames[k]||k).replaceAll('renown','名声').replaceAll('support','支援');return translated+'：'+(x.values||[]).map(v=>typeof v==='object'?(v.value+'（'+(modelSource(v.sourceId)?.title||'来源记录')+'）'):v).join(' / ')+(x.resolution?'；保留两方记录参与范围计算。':'');}
for(const s of modelData.sources)if(!rankingData.sources.some(x=>x.id===s.id))rankingData.sources.push(s);
document.addEventListener('click',e=>{const el=e.target.closest('button,a');if(!el)return;const d=el.dataset;if(d.modelMode){modelState.mode=d.modelMode;render()}if(d.modelCharacter)showModelCharacter(d.modelCharacter);if(d.modelLegacy){$('#detail-dialog').close();showRankingCharacter(d.modelLegacy)}if('modelReset'in d){modelState.weights=null;render()}if('modelClear'in d){modelState.query='';modelState.filter='all';render()}if('modelMethod'in d){e.preventDefault();const x=$('#model-method');x.open=true;x.scrollIntoView({behavior:'smooth'})}});
document.addEventListener('change',e=>{const map={'model-preset':'preset','model-route':'route','model-build':'build','model-skills':'skills','model-filter':'filter'},key=map[e.target.id];if(key){modelState[key]=e.target.value;if(key==='preset')modelState.weights=null;render()}if(e.target.dataset.modelWeight){const p=modelEngine.presets[modelState.preset];modelState.weights ||=Object.fromEntries(modelEngine.keys.map((k,i)=>[k,p.weights[i]]));modelState.weights[e.target.dataset.modelWeight]=Math.min(100,Math.max(0,Number(e.target.value)||0));render();$('#main .model-weights').open=true;}});
let modelInputTimer;document.addEventListener('input',e=>{if(e.target.id!=='model-query')return;modelState.query=e.target.value;clearTimeout(modelInputTimer);modelInputTimer=setTimeout(()=>{const caret=e.target.selectionStart;render();const field=$('#model-query');field?.focus();try{field?.setSelectionRange(caret,caret)}catch{}},180)});
render();
